import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>KuralaYusha</title>
        <meta name="description" content="Generated by Yusha Kuralay" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        selam
      </main>
    </>
  )
}
