import Head from 'next/head'
import { useState } from 'react'

import NavBar from '../components/NavBar'
import MainPage from '../components/MainPage'

import data from '../data.json'


export default function Home() {
  const [darkMode, setDarkMode] = useState<boolean>(false)
  const [mainData, setMainData] = useState(data)
  

  
  console.log(mainData);
  console.log(darkMode);
  
  return (
    <div id={darkMode ? "dark" : "light"}>
      <Head>
        <title>KuralaYusha</title>
        <meta name="description" content="Generated by Yusha Kuralay" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar setDarkMode={setDarkMode} darkMode={darkMode} />
        <MainPage />
      </main>
    </div>
  )
}
