import Head from 'next/head'
import { useState } from 'react'

import NavBar from '../components/NavBar'
import MainPage from '../components/MainPage'

import projectsData from '../data.json'

export type ProjectData = {
  id: number
  name: string
  image: string[]
  description: string
  link: string
  technologies: string[]
  likes: number
}[]

export default function Home() {
  const datatwo = projectsData
  const [darkMode, setDarkMode] = useState<boolean>(false)
  const [data, setData] = useState(projectsData)

  // console.log({ projectsData })
  // console.log(darkMode)

  return (
    <div id={darkMode ? 'dark' : 'light'}>
      <Head>
        <title>KuralaYusha</title>
        <meta
          name="description"
          content="Generated by Yusha Kuralay"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar setDarkMode={setDarkMode} darkMode={darkMode} />
        <MainPage data={data} />
      </main>
    </div>
  )
}
